const CLIENT_CONNECTION_KEPT_VALUE = 1;
const HALF_NODE_CODE = "2";
const ELECTION_STATUS_PENDING = "ELECTION_STATUS_PENDING";
const ELECTION_STATUS_STARTED = "ELECTION_STATUS_STARTED";
const ELECTION_STATUS_FINISHED = "ELECTION_STATUS_FINISHED";
const AMENDMENT_STATUS_INACTIVE = "Inactive";
const START_MINIG_MESSAGE = "start_mining";
// const CLIENT_URL = "http://localhost:3001/?loader_link=";
const CLIENT_URL = "http://usernode.s3-website-us-east-1.amazonaws.com/?loader_link=";

const MAIN_SERVER_CONNECTION = "http://localhost:4003";

const AMENDMENT_CREATE = "AMENDMENT_CREATE";
const AMENDMENT_UPDATE = "AMENDMENT_UPDATE";
const AMENDMENT_REMOVE = "AMENDMENT_REMOVE";

const NUM_CONST_INT_ZERO = 0;
const NUM_CONST_INT_TWO = 2;

const SUCCESSFULLY_CONNECTED = "SUCCESSFULLY_CONNECTED";


module.exports = {
    CLIENT_CONNECTION_KEPT_VALUE,
    HALF_NODE_CODE,
    ELECTION_STATUS_PENDING,
    ELECTION_STATUS_STARTED,
    ELECTION_STATUS_FINISHED,
    AMENDMENT_STATUS_INACTIVE,
    MAIN_SERVER_CONNECTION,
    START_MINIG_MESSAGE,
    AMENDMENT_CREATE,
    AMENDMENT_UPDATE,
    AMENDMENT_REMOVE,
    NUM_CONST_INT_ZERO,
    NUM_CONST_INT_TWO,
    SUCCESSFULLY_CONNECTED,
    CLIENT_URL
}
